### ISSUE TITLE
about MGNN code?

### ISSUE THREAD

**Issue by xdjwolf** [mxliu/ACTION-Software-for-Functional-MRI-Analysis#2]
I have some confusion.
Why dose the MGNN code inconsistent with the illustration structure in the article "Leveraging Brain Modularity Prior for Interpretable Representation Learning of fMRI" ?

**Comment by xdjwolf** [comment]
I also checked the code associated with MGNN ([https://github.com/justwqq/BMR])  and had the same problem. I can't see the consistency between the code and the model structure diagram in the paper.

**Comment by justwqq** [comment]
Thank you for your interest in our work. I have further updated our code on https://github.com/justwqq/BMR_Code, including detailed explanations for the functions used and their implementations. If you come across any inconsistencies or errors, please feel free to contact me at qqw@email.unc.edu.

**Comment by xdjwolf** [comment]
Thanks for your reply. After carefully reading the paper and analyzing the code line by line, I have a general understanding of your design intention.
